//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        public int OrderID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> WorkerID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Item Item { get; set; }
        public virtual Status Status { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
